In [5]:
import numpy as np

In [7]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

### 1. How many negative numbers are there?

In [9]:
negatives = a < 0
len(a[negatives])

4

### 2. How many positive numbers are there?

In [12]:
positives = a > 0
#len(a[positives])
positives

array([ True,  True,  True,  True, False, False, False, False, False,
       False,  True, False])

### 3. How many even positive numbers are there?

In [14]:
poseven = (a > 0) & (a % 2 == 0)
len(a[poseven])

3

### 4. If you were to add 3 to each data point, how many positive numbers would there be?

In [31]:
(a+3)[(a+3) > 0]

array([ 7, 13, 15, 26,  1,  2,  3,  3,  3,  6])

### 5. If you squared each number, what would the new mean and standard deviation be?

In [26]:
sqr = a ** 2
print(f'New list: {sqr}')
print(f'Mean: {(sqr.mean())}')
print(f'Standard deviation: {np.std(sqr)}')

New list: [ 16 100 144 529   4   1   0   0   0  36   9  49]
Mean: 74.0
Standard deviation: 144.0243035046516


### 6. A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering.

In [28]:
center = a.mean()
centered_a = a - center
centered_a

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

### 7. Calculate the z-score for each data point. Recall that the z-score is given by:

In [30]:
deviation = np.std(a)
meanmean = a.mean()

z = (a-meanmean)/deviation

z

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

### 8. Copy the setup and exercise directions from More Numpy Practice into your numpy_exercises.py and add your solutions.

In [ ]:
#Done in numpy_exercises_part_1.py